### ISSUE TITLE
Corrupt jpeg with uridecodebin

### ISSUE THREAD

**Issue by denisvmedyantsev** [insight-platform/Savant#119]
Trying to process any jpeg image using a module with minimal config and image sink adapter results in a corrupted jpeg image (most of the image surface is gray).

module config:
```
name: test
parameters:
  output_frame:
    codec: jpeg
  batch_size: 1
pipeline:
  source:
    element: uridecodebin
    properties:
      uri: file:///data/sample_720p.jpg
```
run sink adapter `./scripts/run_sink.py image-files ./some-path`

The problem is in the decoding stage of the decodebin. Processing of the same image with the source adapter is ok.
