### ISSUE TITLE
RTSP Source crashes when 'dealer' (and 'req'?) scheme is used while the 'router/rep' is not available for a long period

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#155]
```
nvidia_car_classification-rtsp-server-1     | 2023/04/12 06:43:50 INF [RTSP] [conn 172.20.0.5:34334] closed (EOF)
nvidia_car_classification-module-1          | 2023-04-12 06:43:50,749 [savant.gstreamer.runner] [WARNING] Received warning gst-resource-error-quark: No Sources found at the input of muxer. Waiting for sources. (3). gstnvstreammux.c(2658): gst_nvstreammux_src_push_loop (): /GstPipeline:nvidia_car_classification/GstNvStreamMux:muxer
nvidia_car_classification-module-1          | 2023-04-12 06:43:51,749 [savant.gstreamer.runner] [WARNING] Received warning gst-resource-error-quark: No Sources found at the input of muxer. Waiting for sources. (3). gstnvstreammux.c(2658): gst_nvstreammux_src_push_loop (): /GstPipeline:nvidia_car_classification/GstNvStreamMux:muxer
nvidia_car_classification-module-1          | 2023-04-12 06:43:52,749 [savant.gstreamer.runner] [WARNING] Received warning gst-resource-error-quark: No Sources found at the input of muxer. Waiting for sources. (3). gstnvstreammux.c(2658): gst_nvstreammux_src_push_loop (): /GstPipeline:nvidia_car_classification/GstNvStreamMux:muxer
nvidia_car_classification-module-1          | 2023-04-12 06:43:53,750 [savant.gstreamer.runner] [WARNING] Received warning gst-resource-error-quark: No Sources found at the input of muxer. Waiting for sources. (3). gstnvstreammux.c(2658): gst_nvstreammux_src_push_loop (): /GstPipeline:nvidia_car_classification/GstNvStreamMux:muxer
nvidia_car_classification-module-1          | 2023-04-12 06:43:54,750 [savant.gstreamer.runner] [WARNING] Received warning gst-resource-error-quark: No Sources found at the input of muxer. Waiting for sources. (3). gstnvstreammux.c(2658): gst_nvstreammux_src_push_loop (): /GstPipeline:nvidia_car_classification/GstNvStreamMux:muxer
```

It looks like we met some strange bug. The pipeline was compiling models for a while, after that I saw the next (HLS):
1. very long delay (stub image)
2. fast-moving video (1 or 2 cycles)
3. stub image and errors above.

The source stream was played normally.
The second launch with compiled models was ok.

To find the bug, we need the pipeline to be in starting state for a while. It could break the RTSP source, but it also could break the pipeline. Recommend starting from the source.

Changing the RTSP source's socket from `dealer/router` to `pub/sub` led to normal operation:

```yaml
version: "3.3"
services:
  rtsp-server:
    image: aler9/rtsp-simple-server
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
    environment:
      - RTSP_PROTOCOLS=tcp
  rtsp-stream:
    image: linuxserver/ffmpeg:version-4.4-cli
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    command: -re -stream_loop -1 -i https://eu-central-1.linodeobjects.com/savant-data/nvidia-car-classification/deepstream_sample_720p.mp4 -c copy -bsf:v h264_mp4toannexb -f rtsp rtsp://rtsp-server:8554/nvidia-sample
    healthcheck:
      test: ["CMD", "ffprobe", "rtsp://rtsp-server:8554/nvidia-sample"]
      interval: 5s
      start_period: 5s
  module:
    image: ghcr.io/insight-platform/savant-deepstream:0.2.0-6.2-samples
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../models/nvidia_car_classification:/models
      - ../../downloads/nvidia_car_classification:/downloads
      - .:/opt/app/samples/nvidia_car_classification
    command: samples/nvidia_car_classification/module.yml
    environment:
      - ZMQ_SRC_ENDPOINT=ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SRC_TYPE=SUB
      - ZMQ_SRC_BIND=True
      - ZMQ_SINK_ENDPOINT=ipc:///tmp/zmq-sockets/output-video.ipc
      - ZMQ_SINK_TYPE=PUB
      - ZMQ_SINK_BIND=True
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  rtsp-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.2.0
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      rtsp-stream:
        condition: service_healthy
    environment:
      - ZMQ_ENDPOINT=ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_TYPE=PUB
      - ZMQ_BIND=False
      - RTSP_URI=rtsp://rtsp-server:8554/nvidia-sample
      - SOURCE_ID=nvidia-sample-processed
      - SYNC_OUTPUT=True
    entrypoint: /opt/app/adapters/gst/sources/rtsp.sh
  always-on-sink:
    image: ghcr.io/insight-platform/savant-adapters-deepstream:0.2.0-6.2
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../stub_imgs:/stub_imgs
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    environment:
      - ZMQ_ENDPOINT=ipc:///tmp/zmq-sockets/output-video.ipc
      - ZMQ_TYPE=SUB
      - ZMQ_BIND=False
      - RTSP_URI=rtsp://rtsp-server:8554/nvidia-sample-processed
      - SOURCE_ID=nvidia-sample-processed
      - STUB_FILE_LOCATION=/stub_imgs/smpte100_1280x720.jpeg
    command: python -m adapters.ds.sinks.always_on_rtsp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  zmq_sockets:
```
