### ISSUE TITLE
Add validation of mandatory fields for custom model

### ISSUE THREAD

**Issue by dorgun** [insight-platform/Savant#176]
Add validation of the mandatory fields 'custom_lib_path' and 'engine_create_func_name' in cases when model format is custom. 

```yaml
- element: nvinfer@detector
      name: DetectionModel
      model:
          format: custom
          custom_config_file: yolov2-tiny.cfg
          custom_lib_path: libnvdsinfer_custom_impl_Yolo.so
          engine_create_func_name: NvDsInferYoloCudaEngineGet
```
