### ISSUE TITLE
Make a demo with a pyfunc setting a tag for drawing/encoding based on detected objects

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#244]
The idea is simple. To give a user a universal function to add a tag when certain object classes are detected. 

The function must accept parameters in the form of `kwargs`:

```yaml
detections:
  - model: name1
    labels:
      - l1
      - l2
set_tags: 
  - tagname1
protection_interval_ms: 1000 # min 1 second switch period from state to state
```

Works on a principle: "set if any model/label pair matches".

Create a demo showing how peoplenet model with present and absent people triggers encoding and drawing (loop, module, always-on rtsp)
