### ISSUE TITLE
Conditional pipeline parts load 

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#260]
Introduce `condition`-based blocks like:

```yaml
pipeline:
  elements:
    init_condition: 
      expr: expression-on-config-vars
      value: "something"

    - element: nvinfer@detector
    - element: ...
  elements:
    ...
    ...
  
```

The behavior is static, not dynamic. Multiple `elements` blocks may present.

**Comment by abramov-oleg** [comment]
I propose we use the `Stage` entity for this task https://github.com/insight-platform/Savant/blob/develop/savant/config/schema.py#L331

Currently, the `Stage` is completely unused. We can add an optional field `StageConditon` to the `Stage` that will be filled with expr/value from `init_condition` node in the config.

A few examples of possible pipeline configs after changes (source and sink sections are unchanged and assumed to be defined in the default config).

Single stage, always enabled. Try to support previous syntax

```
pipeline:
    elements:
       - element: nvinfer@detector
       - element: ...
```

Single stage with condition

```
pipeline:
  stages:
    - init_condition:
        expr: expression-on-config-vars
        value: "something"
      elements:
        - element: nvinfer@detector
        - element: ...
```

Two stages, one with condition, other is always enabled

```
pipeline:
  stages:
    - init_condition:
        expr: expression-on-config-vars
        value: "something"
      elements:
        - element: nvinfer@detector
        - element: ... 
    - elements:
        - element: nvinfer@detector
        - element: ...
```
