### ISSUE TITLE
JPG decode artifacts when using uridecodebin pipeline source

### ISSUE THREAD

**Issue by abramov-oleg** [insight-platform/Savant#296]
Using `uridecodebin` pipeline source to read a jpg image, leads to incorrect pipeline input. Example,

```
pipeline:
  source:
    element: uridecodebin
    properties:
      uri: file:///data/test.jpg
# rest of module definition is skipped as not relevant
```
![00000](https://github.com/insight-platform/Savant/assets/20332763/d3d8306c-3d74-4bce-9140-2b5fab9a7b8a)

This occurs because the `decodebin` gstreamer auto-plugging logic uses [nvv4l2decoder](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvvideo4linux2.html) for jpegs but skips the required `jpegparse` element (see note on the linked page).

Possible fixes:
- Fix auto-plugging by forcing `decodebin` to add `jpegparse` (increase the rank of `jpegparse`, add `parsed=true` caps requirements). Unclear if this is going to work.
- Handle this source config by manually building `filesrc` -> `jpegparse` decoding pipeline as is done in `pictures` source adapter.

Temp workarounds:
- Use png
- Use source adapter
