### ISSUE TITLE
Output BBox not drawing

### ISSUE THREAD

**Issue by mnuriyumusak** [insight-platform/Savant#31]
Hi, my module.yml is below, my video mp4 input size is 1944x2592, the problem is, output json successfully founds person and cars and also bbox'es of them, but there are no bbox on output image or video. I think the problem is bbox locations need to be scaled up, however I could not found any configuration about this. Can you please share how can I scale up bbox locations so that I can see them on the output image o videos. 

This is my module.yml
````
name: ${oc.env:MODULE_NAME, 'deepstream_test2'}

parameters:
  output_frame: {json:${oc.env:OUTPUT_FRAME, '{"codec":"jpeg"}'}}
  frame_width: 2592
  frame_height: 1944

pipeline:
  elements:
    - element: nvinfer@detector
      name: peoplenet
      model:
        format: etlt
        remote:
          url: s3://savant-data/models/peoplenet/peoplenet_pruned_v2.0.zip
          checksum_url: s3://savant-data/models/peoplenet/peoplenet_pruned_v2.0.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        
        model_file: resnet34_peoplenet_pruned.etlt  # v2.0 Accuracy: 84.3 Size 20.9 MB

 
        input:
          layer_name: input_1
          shape: [3, 1944, 2592]
        output:
          layer_names: [output_bbox]
````

And here is some rows from output json 
````
{"source_id": "104", "pts": 80000000, "framerate": "25/1", "width": 1280, "height": 720, "dts": null, "duration": 40000000, "codec": "jpeg", "keyframe": true, "metadata": {"objects": []}, "tags": {"location": "/home/argegpu/softwareTeam/cv-pipeline-abdullah/cv-pipeline/InsightFace_Pytorch/data/InterProbe/inputs/videos/s15/s15.mp4"}, "schema": "VideoFrame", "frame_num": 2}
{"source_id": "104", "pts": 120000000, "framerate": "25/1", "width": 1280, "height": 720, "dts": null, "duration": 40000000, "codec": "jpeg", "keyframe": true, "metadata": {"objects": [{"model_name": "Primary_Detector", "label": "Person", "object_id": 0, "bbox": {"xc": 0.31223976612091064, "yc": 0.27872899174690247, "width": 0.036283232271671295, "height": 0.1472644805908203, "angle": 0.0}, "confidence": 0.9695695638656616, "attributes": [], "parent_model_name": null, "parent_label": null, "parent_object_id": null}, {"model_name": "Primary_Detector", "label": "Person", "object_id": 1, "bbox": {"xc": 0.1602877974510193, "yc": 0.5068618655204773, "width": 0.055438458919525146, "height": 0.2115742415189743, "angle": 0.0}, "confidence": 0.899117648601532, "attributes": [], "parent_model_name": null, "parent_label": null, "parent_object_id": null}, {"model_name": "Primary_Detector", "label": "Car", "object_id": 2, "bbox": {"xc": 0.10423523187637329, "yc": 0.047047920525074005, "width": 0.0737493708729744, "height": 0.08167795836925507, "angle": 0.0}, "confidence": 0.7405556440353394, "attributes": [], "parent_model_name": null, "parent_label": null, "parent_object_id": null}]}, "tags": {"location": "/home/argegpu/softwareTeam/cv-pipeline-abdullah/cv-pipeline/InsightFace_Pytorch/data/InterProbe/inputs/videos/s15/s15.mp4"}, "schema": "VideoFrame", "frame_num": 3}
{"source_id": "104", "pts": 160000000, "framerate": "25/1", "width": 1280, "height": 720, "dts": null, "duration": 40000000, "codec": "jpeg", "keyframe": true, "metadata": {"objects": [{"model_name": "Primary_Detector", "label": "Person", "object_id": 0, "bbox": {"xc": 0.31226062774658203, "yc": 0.2789035141468048, "width": 0.03635203838348389, "height": 0.1467110812664032, "angle": 0.0}, "confidence": 0.9607311487197876, "attributes": [], "parent_model_name": null, "parent_label": null, "parent_object_id": null}, {"model_name": "Primary_Detector", "label": "Person", "object_id": 1, "bbox": {"xc": 0.16161800920963287, "yc": 0.5075418949127197, "width": 0.056631267070770264, "height": 0.21095207333564758, "angle": 0.0}, "confidence": 0.8203519582748413, "attributes": [], "parent_model_name": null, "parent_label": null, "parent_object_id": null}, {"model_name": "Primary_Detector", "label": "Car", "object_id": 2, "bbox": {"xc": 0.10289463400840759, "yc": 0.04793255403637886, "width": 0.07455217093229294, "height": 0.08282533288002014, "angle": 0.0}, "confidence": 0.6844093799591064, "attributes": [], "parent_model_name": null, "parent_label": null, "parent_object_id": null}]}, "tags": {"location": "/home/argegpu/softwareTeam/cv-pipeline-abdullah/cv-pipeline/InsightFace_Pytorch/data/InterProbe/inputs/videos/s15/s15.mp4"}, "schema": "VideoFrame", "frame_num": 4}
```
`
