### ISSUE TITLE
Yolo BBox Error

### ISSUE THREAD

**Issue by mnuriyumusak** [insight-platform/Savant#32]
I'm using yolov5s.onnx as model file for detector. However, It gets error about parsing bboxes. I've tried to use convertor but I could not achieve that. What is wrong here? How can I make savant to draw bbox on output with yolov5 model?

``` 
name: mytest

parameters:
  output_frame: ${json:${oc.env:OUTPUT_FRAME, '{"codec":"jpeg"}'}}
  frame_width: 1920
  frame_height: 1080

pipeline:
  elements:
    - element: nvinfer@detector
      name: yolonew
      model:
        format: onnx
        model_file: yolov5s.onnx
        input:
          layer_name: images
          shape: [3, 640, 640]
          scale_factor: 0.0039215697906911373
          maintain_aspect_ratio: true
        batch_size: 1
        
        output:
          layer_names: [output0]
          converter:
            module: savant.converter.yolo_v4
            class_name: TensorToBBoxConverter
          num_detected_classes: 80
          objects:
            - class_id: 0
              label: Person


    - element: drawbin
      module: savant.deepstream.drawbin
      class_name: NvDsDrawBin
      element_type: detector
```
