### ISSUE TITLE
Cannot assign same obj label to multiple object classes

### ISSUE THREAD

**Issue by abramov-oleg** [insight-platform/Savant#365]
For example, group cars and persons into one object group in the nvidia_car_classification demo:

```
...
          objects:
            - class_id: 0
              label: Car
            - class_id: 2
              # was label: Person
              label: Car
...
```

leads to 

```
savant.config.module_config.ModuleConfigException: Element nvinfer@detector:v1(name=Primary_Detector): The key `Car` is expected to be a new one, but it already exists.
```
