### ISSUE TITLE
If orphan object is discovered handle it properly

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#426]
For what "WARN: The object (ID, model, label, box) is an orphan (no parent object is assigned). It is a non-typical case: the object should either have the frame or an ROI object as a parent".

https://github.com/insight-platform/Savant/blob/develop/savant/deepstream/buffer_processor.py#L429-L430

```python
if isinstance(parent_object_meta.bbox, BBox):
    parent_bbox = parent_object_meta.bbox.copy()
```

`parent_object_meta` is `None` here.

```yaml

version: "3.3"
services:
  source-2:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:latest
    volumes:
      - /tmp/video-loop-source-downloads:/tmp/video-loop-source-downloads
    environment:
      - LOCATION=https://eu-central-1.linodeobjects.com/savant-data/demo/deepstream_sample_720p.mp4
      - DOWNLOAD_PATH=/tmp/video-loop-source-downloads
      - ZMQ_ENDPOINT=pub+connect:tcp://HOST_IP:3331
      - SOURCE_ID=source-2
      - SYNC_OUTPUT=True
    entrypoint: /opt/savant/adapters/gst/sources/video_loop.sh
    depends_on:
      module-alpr:
        condition: service_healthy

  # module
  module-alpr:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../models/alpr:/models
      - ../../downloads/alpr:/downloads
      - ..:/opt/savant/modules/alpr
    command: modules/alpr/config/module.yml
    environment:
      - ZMQ_SRC_ENDPOINT=sub+bind:tcp://0.0.0.0:3331
      - ZMQ_SINK_ENDPOINT=pub+bind:tcp://0.0.0.0:3332
      - FPS_PERIOD=10
    ports:
      - "3331:3331"
      - "3332:3332"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ GPU ]
```
