### ISSUE TITLE
KeyError when removing and adding multiple sources

### ISSUE THREAD

**Issue by tomskikh** [insight-platform/Savant#434]
When removing and adding multiple sources a `KeyError` exception raised:
```
 ERROR insight::savant::pyfunc                       > Error in pyfunc do_sink_event()
Aliases for entries in sys.path:
    <distpkg>: /usr/local/lib/python3.8/dist-packages
    <pwd>    : /opt/savant
Traceback (most recent call last):
    <pwd> /gst_plugins/python/pyfunc.py:163     do_sink_event        self.pyfunc.instance.on_event(event)
    <distpkg> /savant/deepstream/pyfunc.py:59   on_event             source_id = self._sources.get_id_by_pad_index(pad_idx)
    <distpkg> /savant/utils/source_info.py:82   get_id_by_pad_index  return self._source_id_by_index[pad_idx]
KeyError: 9
```

This can be reproduced by setting `NUMBER_OF_STREAMS=16` and `SYNC_OUTPUT=False` to `video-loop-source` in samples/opencv_cuda_bg_remover_mog2/docker-compose-multistream.x86.yml:
```
  video-loop-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:latest
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - /tmp/video-loop-source-downloads:/tmp/video-loop-source-downloads
    environment:
      - LOCATION=https://eu-central-1.linodeobjects.com/savant-data/opencv_cuda_bg_remover_mog2/road_traffic.mp4
      - DOWNLOAD_PATH=/tmp/video-loop-source-downloads
      - ZMQ_ENDPOINT=pub+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - SOURCE_ID_PATTERN=road-traffic-processed-%d
      - NUMBER_OF_STREAMS=16
      - SYNC_OUTPUT=False
    entrypoint: /opt/savant/adapters/gst/sources/multi_stream.sh
```
