### ISSUE TITLE
Frame filtering feature

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#537]
When conditional video encoding is used, future pipelines can receive frames without video data. We need a feature to handle them and avoid passing them to the video pipeline.

Like:

```
ingress_frame_filter:
  module: module (in the unified YAML format)
  class_name: Class

egress_frame_filter:
  module: module (in the unified YAML format)
  class_name: Class
```

works with VideoFrame objects (savant-rs)

- True: pass
- False: drop

By default, ingress filters out all frames without video, and egress is bypassed (`return True`). 
Works right after zmq source and before zmq sink.
