### ISSUE TITLE
Pipeline metrics

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#556]
Currently, FpsMetering is implemented inside the pipeline (`savant-rs==0.1.82`). 

It supports the following configuration options:
- `conf.frame_period = 1000` to output stats after every 1000 frames;
- `conf.timestamp_period = 1000` to output stats after every 1000 ms;
- `conf.collection_history` to define how many last stats to keep in the memory (default `100`);

It also automatically logs INFO records when needed:

```
Time-based FPS counter triggered: FPS = 0, OPS = 0, frame_delta = 0, time_delta = 1000, period=[1700124636444, 1700124637444]

or 

Frame-based FPS counter triggered: FPS = inf, OPS = inf, frame_delta = 1, time_delta = 0, period=[1700124636444, 1700124636444]
```

As a developer, you can access the last kept records with

```
recs = p.get_stat_records(10)
```

The `recs` var will contain the following:

```
[
  FrameProcessingStatRecord { 
    id: 3, 
    record_type: Timestamp, 
    ts: 1700124637444, 
    frame_no: 2, 
    object_counter: 6, 
    stage_stats: [
      StageStat { 
        stage_name: "input", 
        queue_length: 0, 
        frame_counter: 2, 
        object_counter: 6, 
        batch_counter: 0 
      }, 
      StageStat {... }, 
      StageStat { ... }, ...]
  }, 
  FrameProcessingStatRecord {}, 
  FrameProcessingStatRecord { 
    id: 0, 
    record_type: Initial, 
    ts: 1700124636444, 
    frame_no: 0, 
    object_counter: 0, 
    stage_stats: [] }]
```

As it can be seen, every `FrameProcessingStatRecord` is a result of the triggering of `Initial` or `Frame` or `Timestamp` counting.

Stage stats contain counters allowing us to monitor data flow and are queued in different stages. There are counters and a gauge (`queue_length`). The implementation also counts objects contained in frames and batches.

We need to add a function to export these data into Prometheus. It must be a separate thread with configured periodicity (1 sec), retrieving the last records and using the `record.id` to distinguish between the old and new ones. 

We need to implement a dashboard in Grafana to show the metrics. The template must be added to the repo. What charts to make:

1. FPS, OPS charts;
2. Queue length charts, like stacks or stacked lines over time-based on the gauge;
3. Total objects processed (scalar, last)
4. Total frames processed (scalar, last)

For the demonstration, use any sample and add the integration showing how it works.

NB: when implementing the function, consider that the exporter can be other than Prometheus, but only one. E.g., OpenTelemetry metric exporter. 

But currently, we focus on Prometheus. Counters, gauges, and other data-types must be used properly to simplify the use. When developing the data structure try accessing the data with Grafana and PromQL to ensure the model is sane.

Under `parameters.telemetry`:

```
parameters:
  telemetry:
    tracing:
      # move tracing here
    metrics:
      frame_period: 1000
      time_period: 1000
      history: 100
      provider: Prometheus
      port: XXXX
```

Implement a user-accessible Pyfunc API allowing access to the statistics with a separate call (no pipeline must be accessible):

```
self.get_runtime_metrics(N)
```

**Comment by tomskikh** [comment]
@bwsw
1. Are `frame_period` and `time_period` mutually exclusive?
2. What's `N` in `self.get_runtime_metrics(N)`?

**Comment by bwsw** [comment]
1. You can use both. Records have discriminant (pipeline.py).
2. N - max records to fetch from the history.

**Comment by tomskikh** [comment]
@bwsw I suggest the following configuration schema
```yaml
parameters:
  telemetry:
    tracing:
      # move tracing here
    metrics:
      frame_period: 1000
      time_period: 1000
      history: 100
      provider: Prometheus
      # similar to tracing.provider_params
      provider_params:
        endpoint: host:port
```
