### ISSUE TITLE
Pipeline Shutdown Handler

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#560]
Implement configuration option allowing setting shutdown handler with YAML.

```
shutdown:
  handler:
    module: name
    class: class
```

Class API receives pipeline stats. Document shutdown handler in the documentation and demonstrate its use in https://github.com/insight-platform/Savant/blob/develop/samples/face_reid/src/index_builder.yml
