### ISSUE TITLE
Using default Savant selector for many object classes leads to slow pipeline initialization

### ISSUE THREAD

**Issue by abramov-oleg** [insight-platform/Savant#590]
Defining a significant, e.g. 80, number of output objects for a detector unit with the `savant.selector.detector.BBoxSelector` selectors will result in a couple minutes wait time at pipeline init stage. 

Example
```yaml
...
        - class_id: 31
          label: snowboard
          selector:
            module: savant.selector.detector
            class_name: BBoxSelector
            kwargs:
              confidence_threshold: 0.5
              nms_iou_threshold: 0.5
            dev_mode: false
        - class_id: 32
          label: sports ball
          selector:
            module: savant.selector.detector
            class_name: BBoxSelector
            kwargs:
              confidence_threshold: 0.5
              nms_iou_threshold: 0.5
...
        - class_id: 79
          label: toothbrush
          selector:
            module: savant.selector.detector
            class_name: BBoxSelector
            kwargs:
              confidence_threshold: 0.5
              nms_iou_threshold: 0.5

```

This long init takes place every run of the module.

The problem occurs because every pyfunc imports the selector module anew, and that result in numba functions compilation.

Affects `rtdetr` sample.
