### ISSUE TITLE
MOG2 background remover sample module gets stuck

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#707]
```
version: "3.3"
services:

  video-loop-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:latest
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - /tmp/video-loop-source-downloads:/tmp/video-loop-source-downloads
    environment:
      - LOCATION=https://eu-central-1.linodeobjects.com/savant-data/demo/road_traffic.mp4
      - DOWNLOAD_PATH=/tmp/video-loop-source-downloads
      - ZMQ_ENDPOINT=req+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - SOURCE_ID=road-traffic-processed
      # - SYNC_OUTPUT=True
    entrypoint: /opt/savant/adapters/gst/sources/video_loop.sh
    depends_on:
      module:
        condition: service_healthy

  module:
    image: ghcr.io/insight-platform/savant-deepstream:latest
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ..:/opt/savant/samples
    command: samples/opencv_cuda_bg_remover_mog2/demo.yml
    environment:
      - ZMQ_SRC_ENDPOINT=rep+bind:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SINK_ENDPOINT=pub+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      - METRICS_FRAME_PERIOD=1000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

1. disable `sync`
2. run: `docker compose -f samples/opencv_cuda_bg_remover_mog2/docker-compose.x86.yml up video-loop-source`

3. Observe in CLI:

```
video-loop-source-1  |  WARN  savant_rs::zeromq::writer                             > Failed to receive message from ZeroMQ socket. Error is [11] Resource temporarily unavailable
video-loop-source-1  |  WARN  savant_rs::zeromq::writer                             > Retrying to receive message from ZeroMQ socket, retries left: 3
```

no errors in the module.

4. stop the loop with Ctrl+C

5. module has high utilization:

![image](https://github.com/insight-platform/Savant/assets/15047882/ce4a2b67-a637-4491-af10-fefd39d51c1b)
