### ISSUE TITLE
%source_id and %src_filename are not respected in image_file sink adapter

### ISSUE THREAD

**Issue by heyryanw** [insight-platform/Savant#772]
Running on 0.2.10, the two params are not respected when used in the `DIR_LOCATION` environment variable. It instead will output to a path like: `/some/path/%source_id-%src_filename`

**Comment by bwsw** [comment]
To fix in:
- 0.2.x
- 0.3.x
- develop

**Comment by bwsw** [comment]
1. images and meta are written to different directories.
2. substitutions do not work well.
3. add `%chunk_idx` to documentation.
4. ensure that when `%src_filename` is missing, it works properly.

To backport to 0.4 and release `0.4.6`

```yaml
  sink:
    image: ghcr.io/insight-platform/savant-adapters-py:latest
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../out:/out
    environment:
      - ZMQ_ENDPOINT=sub+connect:ipc:///tmp/zmq-sockets/output-video.ipc
      - CHUNK_SIZE=100
      - DIR_LOCATION=/out/%source_id/%chunk_idx
      - DEV_MODE=True
    entrypoint: /opt/savant/adapters/python/sinks/image_files.py
```

![image](https://github.com/user-attachments/assets/08c096bc-6ef7-4910-b47e-31315f16c466)
