### ISSUE TITLE
Pipeline Idle monitor

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#782]
Implement stuck state monitor allowing to monitor multiple buffer adapters through Prometheus endpoints and restart designated images when stuck is detected.

```
watch: 
  - buffer: buffer1:1111, 
    queue:
      action: stop
      length: 200
      ignore_after_restart: 60s
      restart: # any 
        - labels: [x,y,z] # all
        - labels: c
    egress:
      action: restart
      restart_cooldown: 60s
      idle: 100s
      restart:
        - labels: x
        - labels: y
    ingress:
      action: restart
      restart_cooldown: 60s
      idle: 50s
      restart:
        - label=z
  - buffer: buffer2:2222    
    ...
```
