### ISSUE TITLE
Extend the artist to support bluring

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#88]
Make it possible to blur with the artist without a custom pyfunc code. Change the PeopleNet demo accordingly. 

The `drawfunc` customization must be removed. The properties must be configured declaratively.

Write parameters validation tests for `draw_func` block to ensure reasonable errors during the initialization.

**Comment by bwsw** [comment]
It looks like the code supports it. Probably need to implement in the declarative configuration.

**Comment by bwsw** [comment]
hierarchical keys, not flat:

```yaml

bounding_box:
  border_color: color
  border_thickness: number
  padding: (left, top, right, bottom: int)

blur: true/false

central_dot:
  radius: r
  color: c

label:
  font: font
  font_scale: scale
  font_size: s
  color: c
  thickness: w
  format: 
    - "Label: {label}"
    - "Track: #{track_id}"
    - ...
```
