### ISSUE TITLE
Argus pipeline input implementation

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#918]
As it is done with uridecodebin, it allows for capturing directly with the pipeline without adapters. The user can specify multiple sensors and their options in the YAML configuration.

Support only L4T environment, not X86.

```yaml
source:
    element: nvarguscamerasrc:
    - camera: 0
      properties: ...
    - camera: 1
      properties: ...
```
